import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class AboutScreen extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _AboutScreenState();
  }
}

class _AboutScreenState extends State<AboutScreen> {
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
      appBar: AppBar(
        title: Text("About App"),
      ),

          body: Stack(
              fit: StackFit.expand,

              children: <Widget>[
                Container(
                  decoration: BoxDecoration(color: Colors.white)
                  ),
                Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  children: <Widget>[
                Expanded(
                  child: SingleChildScrollView(
                    child: new Container(
                          child: Column(
                          mainAxisAlignment: MainAxisAlignment.start,
                          children: <Widget>[
                            Image(
                              image: AssetImage('images/missing-person.jpg'),
                              ),
                            Padding(
                              padding: EdgeInsets.only(top: 20.0, left: 10, right: 10,),

                            child: Text(
                                'Our project is a simple application intended to search for missing people in a certain geological area (The application is specifically designed for Lebanon). It is an application that both the seeker and finder of the missing person are capable of using. One of the problems that Lebanese people face nowadays during these harsh circumstances is that many people go missing for unknown reasons in various Lebanese districts. This applications role is to spread information about the missing people through connecting the seekers and the trackers (finders), thus, raising the probability of finding the missing person. Creating an account is an easy procedure for seekers and finders, it requires them to input their email and password for registration, later they can log in to this account. The seeker is asked to add the missing persons information (full name, age, city, address, description, reward, and an image of the missing person) as well as his/her own phone number. Second, if the missing person was spotted, the finder will contact the seeker on his/her phone number. If the seeker specified a reward for finding the missing person, then the finder will receive the reward. ',
                              textAlign: TextAlign.justify,
                                style: TextStyle(
                                  color: Colors.black,
                                  fontSize: 20,

                                ),
                              ),

                            ),

                            Padding(
                              padding: EdgeInsets.only(top: 120.0),
                            ),
                            Text(
                                'This application is generated by AUB ',
                                textAlign: TextAlign.left,
                                style: TextStyle(
                                  backgroundColor: Colors.red,
                                  color: Colors.black87,
                                  fontSize: 20,
                                  fontWeight: FontWeight.bold,
                                  wordSpacing: 2.0,
                                  letterSpacing: 1.0,
                                ),
                              ),
                            Text(
                              'junior students:',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                backgroundColor: Colors.red,
                                color: Colors.black87,
                                fontSize: 20,
                                fontWeight: FontWeight.bold,
                                wordSpacing: 2.0,
                                letterSpacing: 1.0,
                              ),
                            ),
                            Padding(
                              padding: EdgeInsets.only(top: 20.0),
                            ),
                            Image.asset('images/Ahmad-Ghandour.jpg', width: 90, height: 95, ),

                              Text(
                                'Ahmad \nGhandour',
                                textAlign: TextAlign.justify,
                                style: TextStyle(
                                  color: Colors.black,
                                  fontSize: 14,
                                ),
                              ),
                            Padding(
                              padding: EdgeInsets.only(top: 20.0),
                            ),
                              Image.asset('images/Jana-El-Kari.jpg', width: 90, height: 100,),

                              Text(
                                'Jana \nEl-Kari',
                                textAlign: TextAlign.justify,
                                style: TextStyle(
                                  color: Colors.black,
                                  fontSize: 14,
                                ),
                              ),
                            Padding(
                              padding: EdgeInsets.only(top: 20.0),
                            ),
                            Image.asset('images/Jana-Ibrahim-El-Husseini.jpg', width: 90, height: 100,),
                            Text(
                                'Jana Ibrahim \nEl Husseini',
                                textAlign: TextAlign.justify,
                                style: TextStyle(
                                  color: Colors.black,
                                  fontSize: 14,
                                ),
                              ),
                            Padding(
                              padding: EdgeInsets.only(top: 20.0),
                            ),
                            Image.asset('images/Jana-Kanafani.jpg', width: 90, height: 100,),
                              Text(
                                'Jana \nKanafani',
                                textAlign: TextAlign.justify,
                                style: TextStyle(
                                  color: Colors.black,
                                  fontSize: 14,
                                ),
                              ),
                            Padding(
                              padding: EdgeInsets.only(top: 20.0),
                              ),
                      ],
                    ),
                  ),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}
